export const MOTIVATIONAL_QUOTES = [
  "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito. - Albert Schweitzer",
  "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
  "La única manera de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
  "El futuro pertenece a quienes creen en la belleza de sus sueños. - Eleanor Roosevelt",
  "No dejes que el ayer ocupe demasiado del hoy. - Will Rogers",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
  "Cree que puedes y casi lo habrás logrado. - Theodore Roosevelt",
  "La disciplina es el puente entre las metas y los logros. - Jim Rohn",
  "Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta. - Henry Ford",
  "Haz de cada día tu obra maestra. - John Wooden",
  "La mejor preparación para el mañana es hacer lo mejor que puedas hoy. - H. Jackson Brown Jr.",
  "El secreto de seguir adelante es empezar. - Mark Twain",
  "No midas tu éxito por lo que logras, sino por la oposición que has superado para alcanzar tus metas. - Booker T. Washington",
  "La excelencia no es un acto, sino un hábito. - Aristóteles",
  "Para ser el mejor, debes ser capaz de soportar lo peor. - Anónimo",
  "Tus clientes más descontentos son tu mayor fuente de aprendizaje. - Bill Gates",
  "La única limitación a nuestros logros de mañana serán nuestras dudas de hoy. - Franklin D. Roosevelt",
  "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
  "No busques los errores, busca un remedio. - Henry Ford",
  "Si la oportunidad no llama, construye una puerta. - Milton Berle",
  "Los grandes resultados requieren grandes ambiciones. - Heródoto",
  "La motivación es lo que te pone en marcha. El hábito es lo que hace que sigas. - Jim Rohn",
  "Los líderes no crean seguidores, crean más líderes. - Tom Peters",
  "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos. - Michael Jordan",
  "Tu tiempo es limitado, así que no lo pierdas viviendo la vida de otra persona. - Steve Jobs",
  "La mejor forma de predecir el futuro es creándolo. - Peter Drucker",
  "El éxito no se logra solo con cualidades especiales. Es sobre todo un trabajo de constancia, de método y de organización. - J.P. Sergent",
  "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas. - Jack Canfield",
  "El coraje es la resistencia al miedo, el dominio del miedo, no la ausencia de miedo. - Mark Twain",
  "La acción es la clave fundamental para todo éxito. - Pablo Picasso",
  "El secreto para salir adelante es comenzar. - Sally Berger",
  "La perseverancia no es una carrera larga; son muchas carreras cortas una tras otra. - Walter Elliot",
  "Lo que haces hoy puede mejorar todos tus mañanas. - Ralph Marston",
  "Las oportunidades grandes nacen de haber sabido aprovechar las pequeñas. - Bill Gates",
  "No hay atajos para llegar a los lugares que realmente valen la pena. - Beverly Sills",
  "Un líder es aquel que conoce el camino, hace el camino y muestra el camino. - John C. Maxwell",
  "Hazlo con pasión o no lo hagas. - Anónimo",
  "La productividad nunca es un accidente. Siempre es el resultado de un compromiso con la excelencia, la planificación inteligente y el esfuerzo enfocado. - Paul J. Meyer",
  "El poder de la concentración es la diferencia entre la mediocridad y la grandeza. - Anónimo",
  "No encuentres excusas, encuentra soluciones. - Anónimo",
  "Concéntrate en ser productivo, no en estar ocupado. - Tim Ferriss",
  "Tu actitud, no tu aptitud, determinará tu altitud. - Zig Ziglar",
  "El trabajo duro supera al talento cuando el talento no trabaja duro. - Tim Notke",
  "La paciencia, la persistencia y la transpiración hacen una combinación imbatible para el éxito. - Napoleon Hill",
  "Nunca es tarde para ser lo que podrías haber sido. - George Eliot",
  "Si quieres volar, tienes que renunciar a las cosas que te pesan. - Toni Morrison",
  "Quien tiene un porqué para vivir puede soportar casi cualquier cómo. - Friedrich Nietzsche",
  "Siempre parece imposible hasta que se hace. - Nelson Mandela",
  "La visión sin acción es solo un sueño. La acción sin visión es pasar el tiempo. La visión con acción puede cambiar el mundo. - Joel Barker",
  "El destino no es cuestión de casualidad, sino de elección. No es algo que se deba esperar, sino algo que se debe lograr. - William Jennings Bryan",
  "El verdadero líder siempre lidera con el ejemplo, inspirando a otros a alcanzar su máximo potencial. - Anónimo",
  "La confianza en uno mismo es el primer secreto del éxito. - Ralph Waldo Emerson",
  "No sueñes con el éxito, trabaja para conseguirlo. - Estée Lauder",
  "La innovación distingue a los líderes de los seguidores. - Steve Jobs",
  "El éxito es gustarte a ti mismo, gustarte lo que haces y gustarte cómo lo haces. - Maya Angelou",
  "No te detengas cuando estés cansado, detente cuando hayas terminado. - Anónimo",
  "El crecimiento y la comodidad no coexisten. - Ginni Rometty",
  "Apunta a la luna. Si fallas, podrías golpear una estrella. - W. Clement Stone",
  "La mejor manera de empezar es dejar de hablar y comenzar a actuar. - Walt Disney",
  "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste. - Newt Gingrich",
  "El éxito suele llegar a quienes están demasiado ocupados para buscarlo. - Henry David Thoreau"
];
